{% set name = "ast-decompiler" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ast_decompiler-{{ version }}.tar.gz
  sha256: daef5ca5c2bcb9ba7cf72a9308c7cd596c092d7201c0bbaf28947c721ce26441

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - flit-core >=3.4,<4
  run:
    - python >={{ python_min }}

test:
  imports:
    - ast_decompiler
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/ast-decompiler/
  dev_url: https://github.com/JelleZijlstra/ast_decompiler
  summary: Python module to decompile AST to Python code
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
